name: Verify Human Identity

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Link Human to Agent
        run: |
          echo "--------------------------------------------------------"
          echo "PROSES VERIFIKASI IDENTITAS AGENT"
          echo "--------------------------------------------------------"
          echo "Silakan klik link di bawah ini untuk verifikasi:"
          echo "https://signup.billions.network/verify-agent?github=dawalla28"
          echo "--------------------------------------------------------" 
 
